---
- name: Set the state of a virtual machine to poweredoff using MoID
  vmware_guest_powerstate:
    hostname: "{{ vaddr }}"
    username: "{{ vusrname }}"
    password: "{{ vpasswd }}"
    validate_certs: no
    folder: "/{{ vdd }}/vm/"
    name: "{{ vmname }}"
    state: powered-off
    state_change_timeout: 90
