- name: Clone the Centos 8 Template
  vmware_guest:
    hostname: "{{ vaddr }}"
    username: "{{ vusrname }}"
    password: "{{ vpasswd }}"
    validate_certs: False
    name: "{{ vmname }}"
    template: "{{ vtmplate }}"
    datacenter: "{{ vdd }}"
    folder: "{{ vfoldr }}"
    state: poweredon
    cluster: "{{ vclustr }}"
    wait_for_ip_address: yes
  register: result
  notify: 
    - li-counter
    - git-adall

- name: print output
  debug: 
    msg:
    - "{{result.instance.ipv4}}"
