- name: install epel-release package
  dnf:
    name: epel-release
    state: latest

- name: enable powertools
  ini_file:
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
    section: PowerTools
    option: enabled
    value: "1"
  notify:
    - yum update cache

- name: install R package
  yum:
    name: R
    state: latest
