---
- name: Set the state of a virtual machine to poweron using MoID
  vmware_guest_powerstate:
    hostname: "{{ vaddr }}"
    username: "{{ vusrname }}"
    password: "{{ vpasswd }}"
    validate_certs: no
    folder: "/{{ vdd }}/vm/"
    name: "{{ vmname }}"
    state: powered-on

- name: wait for the VM to be powered on
  wait_for:
    timeout: 120
